name: Python release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish-and-release:
    name: Publish and release distributions

    runs-on: ubuntu-latest

    permissions:
      contents: write
      discussions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Package and publish
        uses: EffectiveRange/python-package-github-action@v2
        with:
          use-devcontainer: 'true'
          container-config: 'amd64-container'
          debian-dist-type: 'fpm-deb'
          install-packaging-tools: 'false'
      - name: Release
        uses: EffectiveRange/version-release-github-action@v1


