name: Test and Release

on:
  push:
    tags:
      - "v*.*.*"


jobs:

  release:
    if: startsWith(github.ref, 'refs/tags/')

    name: Publish and release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Package and publish
        uses: EffectiveRange/python-package-github-action@v2
        with:
          use-devcontainer: 'true'
          container-config: 'amd64-container'
          debian-dist-type: 'fpm-deb'
          install-packaging-tools: 'false'
      - name: Release
        uses: EffectiveRange/version-release-github-action@v1

